# Generated by Django 5.2.9 on 2025-12-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на зображення'),
        ),
    ]
