# Generated by Django 5.2.9 on 2025-12-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ідентифікатор продукту')),
                ('name', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('description', models.TextField(verbose_name='Опис продукту')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продукту')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступність продукту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
    ]
