# Generated by Django 5.2.9 on 2026-01-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_constant',
            field=models.CharField(default='CONSTANT_VALUE', max_length=50, verbose_name='Тестове константне поле'),
        ),
    ]
