# Generated by Django 5.2.9 on 2026-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_test_constant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_constant',
        ),
        migrations.AddField(
            model_name='product',
            name='test_field',
            field=models.CharField(blank=True, default='test', max_length=100, null=True, verbose_name='Тестове поле'),
        ),
    ]
