# Generated by Django 5.2.9 on 2026-01-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_test_constant_product_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_field',
        ),
    ]
